from setup.misc import SCREEN_WIDTH, SCREEN_HEIGHT 

BLOCK_WIDTH, BLOCK_HEIGHT = (150, 110)
PORT_RADIUS = 12
WIRE_WIDTH = 8

SIDEBAR_INIT_WIDTH = 150

TEXTBOX_WIDTH = SCREEN_WIDTH // 3
TEXTBOX_HEIGHT = SCREEN_HEIGHT // 6

BUTTON_WIDTH = 200
BUTTON_HEIGHT = 100
BUTTON_SPACING = 30
BUTTON_START_Y = 150

SLIDER_WIDTH = 40
SLIDER_HEIGHT = 300
SLIDER_SPACING = 50
LABEL_SPACING = 20
TEXT_LABEL_WIDTH = 370
TEXT_LABEL_HEIGHT = 55
MESSAGE_PADDING = 40

IO_LABEL_OFFSET = 15

PAUSE_BUTTON_COLS = 3

GRID_WIDTH = PAUSE_BUTTON_COLS * BUTTON_WIDTH + (PAUSE_BUTTON_COLS - 1) * BUTTON_SPACING
BUTTON_START_X = SCREEN_WIDTH // 2 - GRID_WIDTH // 2

MACRO_OVERLAY_WIDTH = SCREEN_WIDTH // 2
MACRO_OVERLAY_HEIGHT = SCREEN_HEIGHT // 2